/* eslint-disable @next/next/no-script-component-in-head */
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Header from "../components/Header/Header";
import Brief from "../components/Brief/Brief";
import Screen from "../components/Screen/Screen";
import Video from "../components/Video/Video";
import ScoreTable from "../components/ScoreTable/ScoreTable";
import Footer from "../components/Footer/Footer";
import styled from "styled-components";
import Script from "next/script";

const Container = styled.div`
	background-image: url("/background_dots.png");

	border-left: 2px solid black;
	background-attachment: fixed;
`;

export default function Home() {
	return (
		<>
			<Head>
				<title>Rmbl</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<meta name="theme-color" content="#0B1115"></meta>
				<Script
					src="https://www.googletagmanager.com/gtag/js?id=G-N0XLCYWQ2P"
					strategy="afterInteractive"
				/>
				<Script id="google-analytics" strategy="afterInteractive">
					{`
          window.dataLayer = window.dataLayer || [];
          function gtag(){window.dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-N0XLCYWQ2P');
        `}
				</Script>
			</Head>
			<Container>
				<Header />

				{/* <Video /> */}
				<Brief />

				<Screen />
				<ScoreTable />
				<Footer />
			</Container>
		</>
	);
}
