import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Header from "../components/Header/Header";
import Brief from "../components/Brief/Brief";
import Screen from "../components/Screen/Screen";
import Video from "../components/Video/Video";
import ScoreTable from "../components/ScoreTable/ScoreTable";
import Footer from "../components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Header />
				<Brief />
				<Screen image="/Screen1_figma.png" />
				{/* <Video /> */}
				<ScoreTable />
				<Footer />
			</main>
		</>
	);
}
