import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Header from "../components/Header/Header";
import Brief from "../components/Brief/Brief";
import Screen from "../components/Screen/Screen";
import Video from "../components/Video/Video";
import ScoreTable from "../components/ScoreTable/ScoreTable";
import Footer from "../components/Footer/Footer";
import styled from "styled-components";

const Container = styled.div`
	background-image: url("/background_dots.png");

	border-left: 2px solid black;
	background-attachment: fixed;
`;

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<meta name="theme-color" content="#0B1115"></meta>
			</Head>
			<Container>
				<Header />

				{/* <Video /> */}
				<Brief />

				<Screen />
				<ScoreTable />
				<Footer />
			</Container>
		</>
	);
}
